name: Replace Links in README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      run: |
        cd .github/actions/replace-link
        npm install
    - name: Run Replace Link Action
      id: replace-link
      uses: ./.github/actions/replace-link
      with:
        input-file: 'README.md' # This can be omitted since it's the default
        output-file: 'index.md' # This can be omitted since it's the default
    - name: Print Updated Content
      run: cat ${{ steps.replace-link.outputs.new-content-path }}

